FROM cern/slc6-base:latest

RUN yum check-update && yum install yum install "http://ftp.scientificlinux.org/linux/scientific/6x/external_products/softwarecollections/yum-conf-softwarecollections-2.0-1.el6.noarch.rpm"
